### ISSUE TITLE
The SDK don't feels like Mobile. Also due to less practical documentation, hard to figure it out.

### ISSUE THREAD

**Issue by AaradhyaGopalNepal** [khalti/checkout-sdk-flutter#2]
**Describe the bug**
I am using this SDK to migrate from the old deprecated [khalti_flutter](https://docs.khalti.com/checkout/flutter/khalti-flutter/). But this SDK is using web view for payment. Being a passionate mobile developer, I think showing a web view on mobile doesn't feel so good to the user. I understand that in things like payment, security is a major concern over user experience, but still, there could be a path where we might consider both. In the end, mobile is all about giving users some functionality with the best user experience.

Also since this is a new way, there are no mentors to guide us about how to implement this SDK. So making some medium posts, or even better some YouTube videos could be very helpful. This might sound like a small concern, but no matter how good a system is, if there is no proper visual examples how can someone use it? On the Khalti website, there is documentation but I don't think it's enough, I couldn't understand it, maybe not other users could, plus they have no one to guide, them since its something new.

My bug report might not feel like a bug report, but its a feedback to the package to use Mobile UI and make some proper documentation. 

You can ignore this paragraph but, the flutter version required to support this SDK is too high, due to which I have to download the GitHub repo reduce the version, and make it run. I will update my flutter version later ;-)

**Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22631.3296], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.86.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.

**Comment by Biplab-Dutta** [comment]
Hi @AradhyaNepal. Thank you for your feedback.
Yes, the new implementation uses WebView under the hood to serve the payment gateway page. That's because we have many other platforms to support as well (android, iOS, flutter, web). The web section is powered by flutter too in our case.
The main reason we leaned towards this approach is, if any change is made in the payment portal (which is essentially a web page), then that would get reflected in all the SDKs.
If a small change is to be made and if that change needs to be worked on across every SDK, it would become very time consuming and expensive for us.
This explains _Why webview_.

The version constraint is a bit higher in the new SDK. That was intentional as well as we don't believe in lagging behind. We are always trying to remain up-to-date with flutter and dart, providing all the latest language support and all. While I understand your concern if one is using a bit older SDK version, we don't plan on lowering the SDK constraint just yet.
We might think about it though as I will have a discussion around it with the team.

And regarding the docs not being available on YouTube and Medium and all, yes, since the SDK is very new, we don't have much of resources regarding its implementation. But you can still suggest how we can make existing README and website docs more comprehensive.

Finally, thank you for trying out the new SDK. Let us know if you happen to encounter any bugs or issues and we will work on it asap.

Closing the issue for now as it's not really a bug report. Feel free to open up a new issue if you happen to encounter a bug.
